// <auto-generated />
namespace BankIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correct_mistakes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correct_mistakes));
        
        string IMigrationMetadata.Id
        {
            get { return "201805030848126_correct_mistakes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
