// <auto-generated />
namespace BankIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedclientIdandserviceTypeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedclientIdandserviceTypeId));
        
        string IMigrationMetadata.Id
        {
            get { return "201805071220385_added-clientId-and-serviceTypeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
